import json
import os
from flask import Flask, render_template, send_from_directory
import logging

app = Flask(__name__)

# --- Configuration ---
SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))
DATA_FILE = os.path.join(SCRIPT_DIR, "dashboard_data.json")
CHART_FILE_NAME = "chart.png" # The name of the chart file generated by the bot

# Disable Flask's default logging to avoid duplicate output with the bot's logger
log = logging.getLogger('werkzeug')
log.setLevel(logging.ERROR)

# --- Routes ---
@app.route('/')
def home():
    """Serves the main dashboard page."""
    data = {}
    try:
        # Load data from the JSON file written by the bot
        with open(DATA_FILE, 'r') as f:
            data = json.load(f)
    except FileNotFoundError:
        # If the file doesn't exist yet, use default values
        data = {
            "price": "N/A",
            "sma": "N/A",
            "position": "N/A",
            "signal": "N/A"
        }
    except json.JSONDecodeError:
         data = {
            "price": "Error",
            "sma": "Error",
            "position": "Error",
            "signal": "Error"
        }

    return render_template('index.html', data=data, chart_file=CHART_FILE_NAME)

@app.route('/charts/<filename>')
def send_chart(filename):
    """Serves the chart image."""
    return send_from_directory(SCRIPT_DIR, filename)

if __name__ == "__main__":
    print("--- Starting Dashboard ---")
    print("Open your browser and go to http://127.0.0.1:5000")
    app.run(debug=False, port=5000) 